CREATE TABLE IF NOT EXISTS texts (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  topic TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
